### ISSUE TITLE
xslt: Shouldn't the first letter be lowercase?

### ISSUE THREAD

**Issue by trondhuso** [iptc/sportsjs-dev#11]
I believe the first letter in the json objects and parameters should be lower-cased. Now the first letter is upper case.

**Comment by trondhuso** [comment]
Johan: Remember to push the latest corrections in the XSLT

**Comment by jolla56** [comment]
This is fixed but there were old xslts still in the repo. I removed thoose and added some comments to the proper ones. There is one for xslt 1 and one for xslt2.
